### ISSUE TITLE
How can i put on Prometheus config, the scrape statement?

### ISSUE THREAD

**Issue by JohnWillker** [slok/ecs-exporter#8]
I trie run a docker container and run ok, but if i trie collect via prometheus.yml, don't work, how can i do that? Please i really need that.

**Comment by JohnWillker** [comment]
or how to use like a service

**Comment by JohnWillker** [comment]
my doubt is how can i put -aws.region on docker-compose? it is var env?

**Comment by marji** [comment]
@JohnWillker This is a snippet from my docker-compose.yml:
```
version: '3'

services:
  ecs-exporter:
    image: "slok/ecs-exporter:latest"
    command:
      - '-aws.region=ap-west-1'
    ports:
      - 9222:9222
    networks:
      - metrics
```
